name: database_repository
description: Dart package which manages database queries.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  firebase_core: ^0.5.3
  meta: ^1.2.4
  cloud_firestore: ^0.14.4
  authentication_repository:
    path: ../authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3